default:
  default_args:
    catchup: false,
    owner: "default_owner"
    start_date: 2024-11-11
    on_success_callback_name: print_hello_from_callback
    on_success_callback_file: $CONFIG_ROOT_DIR/print_hello.py
  schedule: "0 1 * * *"
  on_failure_callback_name: print_hello_from_callback
  on_failure_callback_file: $CONFIG_ROOT_DIR/print_hello.py


# ----8<---   [ start: environment_variable_example ]
example_multiple1:
  default_args:
    owner: "custom_owner"
  description: "this is an example dag"
  schedule: "0 3 * * *"
  render_template_as_native_obj: True
  dag_display_name: "Pretty Example DAG"
  tasks:
    - task_id: "task_1"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 1"
    - task_id: "task_2"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 2"
      dependencies: [task_1]
    - task_id: "task_3"
      operator: airflow.providers.standard.operators.python.PythonOperator
      python_callable_name: print_hello
      python_callable_file: $CONFIG_ROOT_DIR/print_hello.py
      dependencies: [task_1]
# ----8<---   [ end: environment_variable_example ]

example_multiple2:
  default_args:
    timezone: Europe/Amsterdam
  tasks:
    - task_id: "task_1"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 1"
    - task_id: "task_2"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 2"
      dependencies: [task_1]
    - task_id: "task_3"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 3"
      dependencies: [task_1]

example_multiple3:
  tasks:
    - task_id: "task_1"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 1"
    - task_id: "task_2"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 2"
      dependencies: [task_1]
    - task_id: "task_3"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 3"
      dependencies: [task_1]

example_multiple4:
  description: "this dag uses task groups"
  task_groups:
    task_group_1:
      tooltip: "this is a task group"
      dependencies: [task_1]
  tasks:
    - task_id: "task_1"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 1"
    - task_id: "task_2"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 2"
      task_group_name: task_group_1
    - task_id: "task_3"
      operator: airflow.providers.standard.operators.python.PythonOperator
      python_callable_name: print_hello
      python_callable_file: $CONFIG_ROOT_DIR/print_hello.py
      task_group_name: task_group_1
      dependencies: [task_2]
    - task_id: "task_4"
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: "echo 1"
      dependencies: [task_group_1]
