datasets:
  - name: dataset_custom_1
    uri: s3://bucket-cjmm/raw/dataset_custom_1
  - name: dataset_custom_2
    uri: s3://bucket-cjmm/raw/dataset_custom_2
  - name: dataset_custom_3
    uri: s3://bucket-cjmm/raw/dataset_custom_3